import { Application, ApplicationStatus } from "@/types/application";

export const DEFAULT_PROGRAMS: Application[] = [
  {
    id: "smp-uq-ochsner",
    programName: "Doctor of Medicine (MD) Program",
    university: "University of Queensland / Ochsner Health",
    deadline: "2026-08-10",
    status: "Researching",
    degreeType: "M.D. (Graduate-Entry)",
    gpaRequirement: "5.0 / 7.0 (or ~3.0+ US)",
    mcatRequirement: "504+ minimum",
    appFee: "A$150 (~$100 USD)",
    portalUrl: "https://ochsner.uq.edu.au/admissions",
    transcriptsSent: false,
    lorsRequested: false,
    essayCompleted: false,
    notes: "Direct 4-year MD for US citizens/permanent residents. Years 1-2 in Brisbane Australia, Years 3-4 clinical at Ochsner Health New Orleans. Rolling admissions with MMI interview.",
    updatedAt: "2026-09-02T10:30:00.000Z",
  },
  {
    id: "smp-georgetown",
    programName: "Special Master's Program in Physiology",
    university: "Georgetown University",
    deadline: "2026-05-15",
    status: "In Progress",
    degreeType: "M.S. Physiology",
    gpaRequirement: "3.0+",
    mcatRequirement: "500+",
    appFee: "$90",
    portalUrl: "https://som.georgetown.edu/smp/",
    transcriptsSent: true,
    lorsRequested: true,
    essayCompleted: false,
    notes: "Direct linkage to Georgetown School of Medicine. Medical school curriculum parallel.",
    updatedAt: "2026-09-02T10:30:00.000Z",
  },
  {
    id: "smp-bu-mams",
    programName: "Master of Arts in Medical Sciences (MAMS)",
    university: "Boston University",
    deadline: "2026-06-01",
    status: "Researching",
    degreeType: "M.A. Medical Sciences",
    gpaRequirement: "3.0+",
    mcatRequirement: "505+",
    appFee: "$100",
    portalUrl: "https://www.bumc.bu.edu/gms/mams/",
    transcriptsSent: false,
    lorsRequested: false,
    essayCompleted: false,
    notes: "Top placement into US MD/DO programs. 1 or 2-year thesis option.",
    updatedAt: "2026-09-02T10:30:00.000Z",
  },
  {
    id: "smp-temple",
    programName: "Post-Bacc Pre-Med / Master of Science",
    university: "Temple University (Katz)",
    deadline: "2026-04-30",
    status: "Submitted",
    degreeType: "Post-Bacc / MS",
    gpaRequirement: "3.2+",
    mcatRequirement: "500+",
    appFee: "$75",
    portalUrl: "https://medicine.temple.edu/education/postbaccalaureate-programs",
    transcriptsSent: true,
    lorsRequested: true,
    essayCompleted: true,
    notes: "Requires CASPer assessment. Committee letter sent directly.",
    updatedAt: "2026-09-02T10:30:00.000Z",
  },
];
